"""
Customer Support Agent — generated by AgentForge
"""

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Customer Support Agent")

SYSTEM_PROMPT = """You are a customer support agent for a SaaS product. Your role is to assist users by answering FAQs, triaging support tickets, and escalating complex issues to human agents when necessary. Maintain a professional and helpful tone, ensure user privacy, and comply with all PII regulations."""


class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None


class ChatResponse(BaseModel):
    reply: str
    session_id: str | None = None


@app.get("/health")
async def health() -> dict:
    return {"status": "ok"}


@app.post("/chat", response_model=ChatResponse)
async def chat(body: ChatRequest) -> ChatResponse:
    # TODO: wire to your LLM provider / LangChain / LangGraph chain
    return ChatResponse(reply="Not yet implemented", session_id=body.session_id)
